apiVersion: v1
kind: Pod
metadata:
 name: es
 namespace: elk
 labels:
  app: es-middleware
spec:
 containers:
 - name: es-middleware
   image: k8s.gcr.io/elasticsearch:v6.2.4 


---
# Service
apiVersion: v1
kind: Service

metadata:
 name: elasticsearch
 namespace: elk

spec:
 selector: 
  app: es-middleware
 ports:
 - port: 9200 
   targetPort: 9200
  
 
