apiVersion: v1
kind: Pod
metadata:
 name: es
 namespace: elk
 labels:
  app: es-middleware
spec:
 containers:
 - name: es-middleware
   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
   env:
   - name: discovery.type
     value: "single-node"  


---
# Service
apiVersion: v1
kind: Service

metadata:
 name: elasticsearch
 namespace: elk

spec:
 selector: 
  app: es-middleware
 ports:
 - name: one
   port: 9200 
   targetPort: 9200
 - name: two
   port: 9300
   targetPort: 9300
 
