apiVersion: v1
kind: Pod
metadata:
 name: es
 namespace: elk
 labels:
  app: es-middleware
spec:
 containers:
 - name: es-middleware
   image: elasticsearch:6.8.6
   ports:
   - containerPort: 9200
     name: db
     protocol: TCP
   - containerPort: 9300
     name: transport
     protocol: TCP
   env:
   - name: discovery.type
     value: single-node
   - name: ELASTICSEARCH_SERVICE_HOST
     value: 0.0.0.0

---
apiVersion: v1
kind: Service

metadata:
  name: elasticsearch
  namespace: elk

spec:
  selector:
   app: es-middleware
  ports:
  - port: 9200
    targetPort: 9200
 
