kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
   app: nginx
spec:
  containers:
    - name: app
      image: k8s.gcr.io/elasticsearch:v6.2.4
      volumeMounts:
      - name: data
        mountPath: /usr/share/elasticsearch/data
      - name: config
        mountPath: /usr/share/elasticsearch/config
         
  volumes:
  - name: data
    nfs:
     server: 172.42.42.100
     path: /home/vagrant/kubedata/elasticsearch/data
  - name: config
    nfs:
     server: 172.42.42.100
     path: /home/vagrant/kubedata/elasticsearch/config
